### PR TITLE
Switch to Python 3

### PR DESCRIPTION
**Pull request by sebastic**
Python 2 is EOL since 2020-01-01, high time to switch to Python 3.

The port is quite straight forward.

XML needs to be read as bytes, because parsing strings with an XML declaration is not supported.

This requires later decoding to create a geometry from the GML.

The `gemeentelijke-indeling.py` script uses [xlrd](https://pypi.org/project/xlrd/) instead of [pyExcelerator](https://pypi.org/project/pyExcelerator/) for Python 3 support.

The remaining changes are mostly `print` & `Exception` syntax, only using `io.StringIO` & `io.BytesIO`, and not settings the default encoding.

### CODE REVIEW

**Comment by stvno** [comment]
`bag/src/bagextract.py` is still using raw_input() which is not a python3 function: https://github.com/sebastic/NLExtract/blob/python3/bag/src/bagextract.py#L52

if you replace it with input() it works

**Comment by sebastic** [comment]
Thanks, fixed in cf831715c10b62c06fcdd2874ac25b1a2c9ce27a.

**Comment by justb4** [comment]
Great work @sebastic ! Give me some time to review, or can @stvno do this? We went through Py2->Py3 with Stetl and GeoHealthCheck (thanks to @borrob!) , only the BAG Extract was remaining...

**Comment by stvno** [comment]
@justb4 I'm now running @sebastic's bagextract on python3, so far it works for: `python3 src/bagextract.py  -c`

and it is currently running `python3 src/bagextract.py  -e inspireadressen.zip`

I'll let you know if I run into any issues

**Comment by sebastic** [comment]
My tests covered:

 * `./bag/bin/bag-extract.sh -f <conf> -c -j`
 * `./bag/bin/bag-extract.sh -f <conf> -e <inspireaddressen>`
 * `./bag/bin/bag-extract.sh -f <conf> -q ./bag/db/script/gemeente-provincie-tabel.sql`
 * `./bag/bin/bag-extract.sh -f <conf> -q ./bag/db/script/adres-tabel.sql`

My inspireaddressen dataset was trimmed down to only the first XML file in every zip file to limit the processing time.

**Comment by stvno** [comment]
@justb4 I've tested it with the full BAG and it works as expected. It has my vote to be merged

**Comment by justb4** [comment]
Los van de reviews wil ik volgende voorstellen: er is lang geen versie van NLExtract uitgegeven. We werken met Milestones waaraan issues en PRs zijn gekoppeld. Er zijn 20 issues gesloten voor komende [Milestone/Versie 1.4.0](https://github.com/nlextract/NLExtract/milestone/11), niet alleen voor BAG. Ik wil eerst deze uitbrengen, als laatste "stabiele Python2 versie" en dan focus op [Milestone/versie 1.5.0](https://github.com/nlextract/NLExtract/milestone/12) waarin dan o.a. deze PR.

**Comment by fsteggink** [comment]
Ik kom erg laat op het feestje, maar nog van harte bedankt @sebastic  :+1:

**Pull request merged**
