### PR TITLE
Use same provincie_gemeente schema as BAGv1.

### PR DESCRIPTION
**Pull request by sebastic**
The changes in this PR add history to the `provincie_gemeente` table like BAGv1 by using the same `gemeentelijke-indeling.xml` as its source.

The XML data is converted to CSV and imported using Stetl.

It requires Stetl changes to support `None` values for empty CSV fields: https://github.com/geopython/stetl/pull/120

See also the discussion in: #311

### CODE REVIEW

**Comment by sebastic** [comment]
Thanks for merging the stetl changes, do you want me to update the submodule in this PR too?

**Comment by justb4** [comment]
> Thanks for merging the stetl changes, do you want me to update the submodule in this PR too?

Yes, ok!

**Comment by sebastic** [comment]
The stetl submodule is updated to [009e39f](https://github.com/geopython/stetl/commit/009e39fcab4bb59d2dc1680bde869afd02d35265) for the `empty_string_is_none` option.

**Comment by sebastic** [comment]
The stelt configuration should replace records, see the discussion in gitter regarding the data in 2018.

The `gemeentelijke-indeling.csv` in this PR contains the fix for Vianen, #337 should be merged before this issue to ensure regenerating the CSV from the XML contains the fix as well.

**Comment by justb4** [comment]
Ok let's go, thanks for patience @sebastic !

**Pull request merged**
